<template>
    <div>
        <h1>Time Entry</h1>
        <v-client-table :data="tableData" :columns="columns" :options="options"></v-client-table>
    </div>
</template>

<script>
import { mapState, mapActions } from 'vuex'

export default {
    computed: {
        ...mapState({
            account: state => state.account,
            users: state => state.users.all
        })
    },
    data: function() {
        return {
            columns: ['Date', 'Category', 'Description', 'Hours'],
            tableData: [
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
                { Date: '01/01/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 6 },
                { Date: '01/02/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 4 },
                { Date: '01/03/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 2 },
                { Date: '01/04/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 1 },
                { Date: '01/05/2019', Category: 'Personal Development', Description: 'Developing an app while work is slow', Hours: 8 },
            ],
            options: {
                filterable: true,

            }
        }
    }
}
</script>
